# -*- coding: utf-8 -*-
"""DL_Part_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAWvDAeeGi2CjXwSNYzN6o20VJenBdfU
"""

from google.colab import drive
drive.mount('/content/drive')

import os
if not os.path.exists('/content/processed'):
    !tar -xzf "/content/drive/MyDrive/Applied-DL-2/Data/processed_upload.tar.gz" -C /content/
    print("Done extracting.")
else:
    print("Already extracted, skipping.")

!ls /content/processed

!ls /content/aac_32/

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/roh1thbharathi/applied-dl-project-2.git
# %cd /content/applied-dl-project-2
!pip install -q -r requirements.txt

import sys
sys.path.insert(0, '/content/applied-dl-project-2/src')
print("Done.")

import os

BASE = "/content/drive/MyDrive/CodecRobust"
os.makedirs(BASE, exist_ok=True)
print("Folder created at:", BASE)

!python src/smoke_test.py

from google.colab import files
uploaded = files.upload()  # select all 3 txt files at once
print("Uploaded:", list(uploaded.keys()))

import os
import shutil

os.makedirs('/content/asvspoof/LA/ASVspoof2019_LA_cm_protocols', exist_ok=True)

for fname in ['ASVspoof2019.LA.cm.train.trn.txt',
              'ASVspoof2019.LA.cm.dev.trl.txt',
              'ASVspoof2019.LA.cm.eval.trl.txt']:
    shutil.move(f'/content/applied-dl-project-2/{fname}',
                f'/content/asvspoof/LA/ASVspoof2019_LA_cm_protocols/{fname}')

print("Done.")
!ls /content/asvspoof/LA/ASVspoof2019_LA_cm_protocols/

ASV_ROOT       = "/content/asvspoof"
PROCESSED_ROOT = "/content"
RESULTS_DIR    = "/content/drive/MyDrive/CodecRobust/results/grl_only"

import os
os.makedirs(RESULTS_DIR, exist_ok=True)
print("Config ready.")
print("ASV_ROOT:", ASV_ROOT)
print("PROCESSED_ROOT:", PROCESSED_ROOT)
print("RESULTS_DIR:", RESULTS_DIR)

!ls /content/uncompressed/train/ | head -10

!ls /content/uncompressed/train/ | grep "LA_T_5796029"

!ls /content/uncompressed/train/ | wc -l

import os

available = set(f.replace('.pt', '') for f in os.listdir('/content/uncompressed/train/'))
print(f"Available train files: {len(available)}")
print("Sample:", list(available)[:3])

import pandas as pd
from pathlib import Path

# Load protocol
proto_path = "/content/asvspoof/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt"
df = pd.read_csv(proto_path, sep=" ", header=None,
                 names=["speaker", "filename", "dash", "system_id", "label"])

# Filter to only available files
available = set(f.replace('.pt', '') for f in os.listdir('/content/uncompressed/train/'))
df_filtered = df[df['filename'].isin(available)].reset_index(drop=True)

print(f"Protocol total: {len(df)}")
print(f"After filtering to available: {len(df_filtered)}")

# Patch ASVspoof2019Preprocessed to filter to available files
import data_utils

original_init = data_utils.ASVspoof2019Preprocessed.__init__

def patched_init(self, asv_root, processed_root, split="train", contrastive=False):
    original_init(self, asv_root, processed_root, split, contrastive)
    # Filter records to only files that exist in preprocessed folder
    available = set(
        f.replace('.pt', '')
        for f in os.listdir(Path(processed_root) / 'uncompressed' / split)
    )
    before = len(self.records)
    self.records = self.records[self.records['filename'].isin(available)].reset_index(drop=True)
    print(f"  [Filter] {split}: {before} → {len(self.records)} (matched preprocessed files)")

data_utils.ASVspoof2019Preprocessed.__init__ = patched_init
print("Patch applied.")

from importlib import reload
import data_utils
loaders = get_dataloaders(
    asv_root=ASV_ROOT,
    preprocessed_root=PROCESSED_ROOT,
    batch_size=4,
    num_workers=0,
    contrastive=False,
    max_samples=100,
)

batch = next(iter(loaders['train']))
print("Waveform shape:", batch['waveform'].shape)
print("Labels:", batch['label'])
print("Codec indices:", batch['codec_idx'])
print("Dataloader OK.")

import torch
import torch.nn as nn
import torch.optim as optim
import math
import time
from pathlib import Path

from model import CodecRobustDetector, ContrastiveLoss
from data_utils import get_dataloaders, N_CODEC_CLASSES
from evaluate import compute_eer, compute_auc

# ── Config ────────────────────────────────────────────────
ALPHA           = 0.5
BETA            = 0.0
USE_CONTRASTIVE = False
EPOCHS          = 30
BATCH_SIZE      = 32
LR              = 3e-4
MAX_SAMPLES     = 3000
EMBED_DIM       = 256
SAVE_EVERY      = 1   # save every epoch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

# ── Data ──────────────────────────────────────────────────
loaders = get_dataloaders(
    asv_root=ASV_ROOT,
    preprocessed_root=PROCESSED_ROOT,
    batch_size=BATCH_SIZE,
    num_workers=0,
    contrastive=USE_CONTRASTIVE,
    max_samples=MAX_SAMPLES,
)

# ── Model ─────────────────────────────────────────────────
model = CodecRobustDetector(embed_dim=EMBED_DIM, n_codec_classes=N_CODEC_CLASSES).to(device)
optimizer = optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS, eta_min=LR/20)
df_crit    = nn.CrossEntropyLoss()
codec_crit = nn.CrossEntropyLoss()
print(f"Params: {sum(p.numel() for p in model.parameters()):,}")

# ── Resume from latest checkpoint if exists ───────────────
out_dir    = Path(RESULTS_DIR)
start_epoch = 1
best_eer    = 1.0

latest_ckpt = sorted(out_dir.glob("checkpoint_epoch_*.pt"))
if latest_ckpt:
    ckpt = torch.load(latest_ckpt[-1], map_location=device)
    model.load_state_dict(ckpt['model_state_dict'])
    optimizer.load_state_dict(ckpt['optimizer_state_dict'])
    start_epoch = ckpt['epoch'] + 1
    best_eer    = ckpt['best_eer']
    print(f"Resumed from epoch {ckpt['epoch']}, best EER so far: {best_eer*100:.2f}%")
else:
    print("No checkpoint found, starting fresh.")

# ── GRL lambda schedule ───────────────────────────────────
def grl_lambda(step, total_steps, lam_max=1.0):
    p = step / max(total_steps, 1)
    return lam_max * (2.0 / (1.0 + math.exp(-10.0 * p)) - 1.0)

# ── Training loop ─────────────────────────────────────────
total_steps = EPOCHS * len(loaders["train"])
step = (start_epoch - 1) * len(loaders["train"])

for epoch in range(start_epoch, EPOCHS + 1):
    model.train()
    t0 = time.time()
    for batch in loaders["train"]:
        lam = grl_lambda(step, total_steps)
        model.set_lambda(lam)
        wf        = batch["waveform"].to(device)
        labels    = batch["label"].to(device)
        codec_idx = batch["codec_idx"].to(device)
        out       = model(wf)
        loss      = df_crit(out["deepfake_logits"], labels) + ALPHA * codec_crit(out["codec_logits"], codec_idx)
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        optimizer.step()
        step += 1
    scheduler.step()

    # ── Dev eval ──────────────────────────────────────────
    model.eval()
    scores, labs = [], []
    with torch.no_grad():
        for batch in loaders["dev"]:
            s = torch.softmax(model(batch["waveform"].to(device))["deepfake_logits"], -1)[:, 1]
            scores.append(s.cpu())
            labs.append(batch["label"])
    scores = torch.cat(scores).numpy()
    labs   = torch.cat(labs).numpy()
    eer    = compute_eer(labs, scores)
    auc    = compute_auc(labs, scores)

    print(f"Epoch {epoch:02d}/{EPOCHS} | EER={eer*100:.2f}% AUC={auc:.4f} | time={time.time()-t0:.1f}s")

    # ── Save best ─────────────────────────────────────────
    if eer < best_eer:
        best_eer = eer
        torch.save(model.state_dict(), out_dir / "best_model.pt")
        print(f"  ✓ Best EER: {best_eer*100:.2f}% — saved")

    # ── Save checkpoint every epoch ───────────────────────
    if epoch % SAVE_EVERY == 0:
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'eer': eer,
            'best_eer': best_eer,
        }, out_dir / f"checkpoint_epoch_{epoch:02d}.pt")
        print(f"  ✓ Checkpoint saved: epoch {epoch}")

print(f"\nDone. Best EER: {best_eer*100:.2f}%")

!ls /content/drive/MyDrive/CodecRobust/results/grl_only/

from model import CodecRobustDetector
from data_utils import N_CODEC_CLASSES

def load_model(checkpoint_path, device):
    model = CodecRobustDetector(embed_dim=256, n_codec_classes=N_CODEC_CLASSES).to(device)
    state = torch.load(checkpoint_path, map_location=device)
    if isinstance(state, dict) and 'model_state_dict' in state:
        model.load_state_dict(state['model_state_dict'])
    else:
        model.load_state_dict(state)
    model.eval()
    return model

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

baseline  = load_model("/content/drive/MyDrive/CodecRobust/results/baseline/best_model.pt", device)
full      = load_model("/content/drive/MyDrive/CodecRobust/results/full_model/best_model.pt", device)
grl_only  = load_model("/content/drive/MyDrive/CodecRobust/results/grl_only/best_model.pt", device)

print("All 3 models loaded.")

!ls /content/uncompressed/dev/ | head -3

test_pt = torch.load('/content/uncompressed/dev/LA_D_1006568.pt', weights_only=True)
test_input = test_pt.unsqueeze(0).to(device)

with torch.no_grad():
    out = baseline(test_input)
    print("Logits:", out['deepfake_logits'])
    print("Softmax:", torch.softmax(out['deepfake_logits'], -1))

with torch.no_grad():
    out_grl = grl_only(test_input)
    print("GRL Logits:", out_grl['deepfake_logits'])
    print("GRL Softmax:", torch.softmax(out_grl['deepfake_logits'], -1))

with torch.no_grad():
    out_full = full(test_input)
    print("Full Logits:", out_full['deepfake_logits'])
    print("Full Softmax:", torch.softmax(out_full['deepfake_logits'], -1))

import pandas as pd
from pathlib import Path

proto_path = Path(ASV_ROOT) / 'LA' / 'ASVspoof2019_LA_cm_protocols' / 'ASVspoof2019.LA.cm.dev.trl.txt'
df = pd.read_csv(proto_path, sep=' ', header=None,
                 names=['speaker','filename','dash','system_id','label'])

available = set(f.replace('.pt','') for f in os.listdir('/content/uncompressed/dev/'))
df = df[df['filename'].isin(available)].reset_index(drop=True)

print(df['label'].value_counts())
print(f"\nRatio: {df['label'].value_counts()['spoof'] / len(df) * 100:.1f}% spoof")

# Find a bonafide sample
proto_path = Path(ASV_ROOT) / 'LA' / 'ASVspoof2019_LA_cm_protocols' / 'ASVspoof2019.LA.cm.dev.trl.txt'
df = pd.read_csv(proto_path, sep=' ', header=None,
                 names=['speaker','filename','dash','system_id','label'])
available = set(f.replace('.pt','') for f in os.listdir('/content/uncompressed/dev/'))
df = df[df['filename'].isin(available)].reset_index(drop=True)

bonafide_file = df[df['label']=='bonafide'].iloc[0]['filename']
spoof_file    = df[df['label']=='spoof'].iloc[0]['filename']

for name, fname, model_name, m in [
    ('bonafide', bonafide_file, 'baseline', baseline),
    ('spoof',    spoof_file,    'baseline', baseline),
    ('bonafide', bonafide_file, 'grl_only', grl_only),
    ('spoof',    spoof_file,    'grl_only', grl_only),
]:
    pt = torch.load(f'/content/uncompressed/dev/{fname}.pt', weights_only=True).unsqueeze(0).to(device)
    with torch.no_grad():
        out = m(pt)
        prob = torch.softmax(out['deepfake_logits'], -1)
        print(f"{model_name} | {name:8s} | bonafide={prob[0,0]:.3f} spoof={prob[0,1]:.3f}")

import torch

# Load same filename from different codec folders and check if they're different
fname = 'LA_D_1006568'

uncompressed = torch.load(f'/content/uncompressed/dev/{fname}.pt', weights_only=True)
mp3_32 = torch.load(f'/content/mp3_32/dev/{fname}.pt', weights_only=True)

print("Are they identical?", torch.allclose(uncompressed, mp3_32))
print("Uncompressed mean:", uncompressed.mean().item())
print("MP3_32 mean:", mp3_32.mean().item())
print("Max difference:", (uncompressed - mp3_32).abs().max().item())

opus_16 = torch.load(f'/content/opus_16/dev/{fname}.pt', weights_only=True)
print("Opus_16 identical to uncompressed?", torch.allclose(uncompressed, opus_16))

import numpy as np
import pandas as pd
import torch
from pathlib import Path
from data_utils import apply_codec, CODEC_CONFIG, codec_tag
from evaluate import compute_eer

@torch.no_grad()
def eval_per_codec_live(model, asv_root, processed_root, device, split='dev', max_samples=1000):
    import os

    # Load protocol
    proto = {'dev': 'ASVspoof2019.LA.cm.dev.trl.txt'}
    proto_path = Path(asv_root) / 'LA' / 'ASVspoof2019_LA_cm_protocols' / proto[split]
    df = pd.read_csv(proto_path, sep=' ', header=None,
                     names=['speaker','filename','dash','system_id','label'])

    # Filter to available files
    available = set(f.replace('.pt','') for f in os.listdir(f'{processed_root}/uncompressed/{split}/'))
    df = df[df['filename'].isin(available)].reset_index(drop=True)
    if max_samples:
        df = df.sample(min(max_samples, len(df)), random_state=42).reset_index(drop=True)

    results = []
    for codec, bitrates in CODEC_CONFIG.items():
        for bitrate in bitrates:
            tag = codec_tag(codec, bitrate)
            all_scores, all_labels = [], []

            for i in range(0, len(df), 32):
                batch = df.iloc[i:i+32]
                wfs, labs = [], []
                for _, row in batch.iterrows():
                    pt = Path(processed_root) / 'uncompressed' / split / f"{row['filename']}.pt"
                    if not pt.exists():
                        continue
                    wav = torch.load(pt, weights_only=True).unsqueeze(0)  # (1, T)
                    wav = apply_codec(wav, 16000, codec, bitrate)          # apply compression
                    wfs.append(wav.squeeze(0))
                    labs.append(0 if row['label'] == 'bonafide' else 1)

                if not wfs:
                    continue
                wf_batch = torch.stack(wfs).to(device)
                s = torch.softmax(model(wf_batch)['deepfake_logits'], -1)[:, 1]
                all_scores.extend(s.cpu().numpy())
                all_labels.extend(labs)

            eer = compute_eer(np.array(all_labels), np.array(all_scores))
            results.append({'codec': tag, 'EER%': round(eer*100, 1)})
            print(f"  {tag:<15} EER={eer*100:.1f}%")

    return pd.DataFrame(results)

print("=== Baseline ===")
df_baseline = eval_per_codec_live(baseline, ASV_ROOT, PROCESSED_ROOT, device)

print("\n=== GRL Only ===")
df_grl = eval_per_codec_live(grl_only, ASV_ROOT, PROCESSED_ROOT, device)

import pandas as pd
from pathlib import Path
import os

proto_path = Path(ASV_ROOT) / 'LA' / 'ASVspoof2019_LA_cm_protocols' / 'ASVspoof2019.LA.cm.dev.trl.txt'
df = pd.read_csv(proto_path, sep=' ', header=None,
                 names=['speaker','filename','dash','system_id','label'])

available = set(f.replace('.pt','') for f in os.listdir(f'{PROCESSED_ROOT}/uncompressed/dev/'))
df = df[df['filename'].isin(available)].reset_index(drop=True)
df_eval = df.sample(min(1000, len(df)), random_state=42).reset_index(drop=True)

print(f"Eval samples: {len(df_eval)}")

# Quick check - just opus codecs for GRL
for bitrate in [16, 32, 64]:
    tag = f'opus_{bitrate}'
    all_scores, all_labels = [], []

    for i in range(0, len(df_eval), 32):
        batch = df_eval.iloc[i:i+32]
        wfs, labs = [], []
        for _, row in batch.iterrows():
            pt = Path(PROCESSED_ROOT) / 'uncompressed' / 'dev' / f"{row['filename']}.pt"
            if not pt.exists():
                continue
            wav = torch.load(pt, weights_only=True).unsqueeze(0)
            wav = apply_codec(wav, 16000, 'opus', bitrate)
            wfs.append(wav.squeeze(0))
            labs.append(0 if row['label'] == 'bonafide' else 1)

        if not wfs:
            continue
        wf_batch = torch.stack(wfs).to(device)
        with torch.no_grad():
            s = torch.softmax(grl_only(wf_batch)['deepfake_logits'], -1)[:, 1]
        all_scores.extend(s.cpu().numpy())
        all_labels.extend(labs)

    eer = compute_eer(np.array(all_labels), np.array(all_scores))
    print(f"GRL {tag}: EER={eer*100:.1f}%")

import torch
torch.cuda.empty_cache()

# Reduce batch size for contrastive training
BATCH_SIZE = 16  # down from 32

import torch
import gc

gc.collect()
torch.cuda.empty_cache()

BATCH_SIZE = 8  # down to 8
MAX_LEN_SEC = 1.5  # shorter clips = less memory

import torch, gc
gc.collect()
torch.cuda.empty_cache()

BATCH_SIZE      = 4
EMBED_DIM       = 128   # down from 256
MAX_SAMPLES     = 1000  # down from 3000

import torch, gc

# Delete all loaded models
del baseline, full, grl_only
del model

gc.collect()
torch.cuda.empty_cache()
print("GPU memory cleared.")
print(f"Free memory: {torch.cuda.mem_get_info()[0]/1e9:.2f} GB")

import os
os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"

import torch, gc
gc.collect()
torch.cuda.empty_cache()

BATCH_SIZE      = 8
EMBED_DIM       = 256
MAX_SAMPLES     = 500   # drastically reduce

import torch
import torch.nn as nn
import torch.optim as optim
import math
import time
from pathlib import Path

from model import CodecRobustDetector, ContrastiveLoss
from data_utils import get_dataloaders, N_CODEC_CLASSES
from evaluate import compute_eer, compute_auc

# ── Config ────────────────────────────────────────────────
ALPHA           = 0.0    # GRL off
BETA            = 0.1    # Contrastive on
USE_CONTRASTIVE = True
EPOCHS          = 30
BATCH_SIZE      = 32
LR              = 3e-4
MAX_SAMPLES     = 3000
EMBED_DIM       = 256
SAVE_EVERY      = 1
RESULTS_DIR     = "/content/drive/MyDrive/CodecRobust/results/contrastive_only"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

# ── Data ──────────────────────────────────────────────────
loaders = get_dataloaders(
    asv_root=ASV_ROOT,
    preprocessed_root=PROCESSED_ROOT,
    batch_size=BATCH_SIZE,
    num_workers=0,
    contrastive=USE_CONTRASTIVE,
    max_samples=MAX_SAMPLES,
    max_len_sec=1.5,
)

# ── Model ─────────────────────────────────────────────────
model = CodecRobustDetector(embed_dim=EMBED_DIM, n_codec_classes=N_CODEC_CLASSES).to(device)
optimizer = optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS, eta_min=LR/20)
df_crit    = nn.CrossEntropyLoss()
codec_crit = nn.CrossEntropyLoss()
con_crit   = ContrastiveLoss(temperature=0.07)
print(f"Params: {sum(p.numel() for p in model.parameters()):,}")

# ── Resume from latest checkpoint if exists ───────────────
out_dir     = Path(RESULTS_DIR)
start_epoch = 1
best_eer    = 1.0

latest_ckpt = sorted(out_dir.glob("checkpoint_epoch_*.pt"))
if latest_ckpt:
    ckpt = torch.load(latest_ckpt[-1], map_location=device)
    model.load_state_dict(ckpt['model_state_dict'])
    optimizer.load_state_dict(ckpt['optimizer_state_dict'])
    start_epoch = ckpt['epoch'] + 1
    best_eer    = ckpt['best_eer']
    print(f"Resumed from epoch {ckpt['epoch']}, best EER: {best_eer*100:.2f}%")
else:
    print("Starting fresh.")

# ── GRL lambda schedule ───────────────────────────────────
def grl_lambda(step, total_steps, lam_max=1.0):
    p = step / max(total_steps, 1)
    return lam_max * (2.0 / (1.0 + math.exp(-10.0 * p)) - 1.0)

# ── Training loop ─────────────────────────────────────────
total_steps = EPOCHS * len(loaders["train"])
step = (start_epoch - 1) * len(loaders["train"])

for epoch in range(start_epoch, EPOCHS + 1):
    model.train()
    t0 = time.time()
    for batch in loaders["train"]:
        lam = grl_lambda(step, total_steps)
        model.set_lambda(lam)
        wf        = batch["waveform"].to(device)
        labels    = batch["label"].to(device)
        codec_idx = batch["codec_idx"].to(device)
        out       = model(wf)
        loss      = df_crit(out["deepfake_logits"], labels) + ALPHA * codec_crit(out["codec_logits"], codec_idx)

        if USE_CONTRASTIVE and "waveform2" in batch:
            wf2   = batch["waveform2"].to(device)
            out2  = model(wf2)
            B     = wf.size(0)
            pairs = torch.stack([out["embedding"], out2["embedding"]], dim=1).view(2*B, -1)
            loss  = loss + BETA * con_crit(pairs)

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        optimizer.step()
        step += 1
    scheduler.step()

    # ── Dev eval ──────────────────────────────────────────
    model.eval()
    scores, labs = [], []
    with torch.no_grad():
        for batch in loaders["dev"]:
            s = torch.softmax(model(batch["waveform"].to(device))["deepfake_logits"], -1)[:, 1]
            scores.append(s.cpu())
            labs.append(batch["label"])
    scores = torch.cat(scores).numpy()
    labs   = torch.cat(labs).numpy()
    eer    = compute_eer(labs, scores)
    auc    = compute_auc(labs, scores)

    print(f"Epoch {epoch:02d}/{EPOCHS} | EER={eer*100:.2f}% AUC={auc:.4f} | time={time.time()-t0:.1f}s")

    if eer < best_eer:
        best_eer = eer
        torch.save(model.state_dict(), out_dir / "best_model.pt")
        print(f"  ✓ Best EER: {best_eer*100:.2f}% — saved")

    if epoch % SAVE_EVERY == 0:
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'eer': eer,
            'best_eer': best_eer,
        }, out_dir / f"checkpoint_epoch_{epoch:02d}.pt")
        print(f"  ✓ Checkpoint saved: epoch {epoch}")

print(f"\nDone. Best EER: {best_eer*100:.2f}%")

